/*
* jquery-form-builder-plugin - JQuery WYSIWYG Web Form Builder
* http://code.google.com/p/jquery-form-builder-plugin/
*
* Revision: ${svn.info.lastRev}
* Version: 0.1
* Copyright 2011 Lim Chee Kin (limcheekin@vobject.com)
*
* Licensed under Apache v2.0 http://www.apache.org/licenses/LICENSE-2.0.html
*
* Date: ${svn.info.lastDate} 
*/
var FormBuilder={options:{fields:"PlainText, SingleLineText, MultiLineText,dropdown,GroupButton,CheckBox,PlainTextHref",tabSelected:0,readOnly:false,tabDisabled:[],formCounter:1,language:"en",settings:{en:{name:"Form",classes:["leftAlign"],heading:"h2",styles:{fontFamily:"default",fontSize:"default",fontStyles:[1,0,0]}},zh_CN:{name:"\u8868\u683c",classes:["rightAlign"],heading:"h2",styles:{fontFamily:"default",fontSize:"default",fontStyles:[1,0,0]}},styles:{color:"default",backgroundColor:"default"}},
_id:"#container",_languages:["en","zh_CN"],_builderPanel:"#builderPanel",_builderForm:"#builderForm",_emptyBuilderPanel:"#emptyBuilderPanel",_paletteTabs:"#paletteTabs",_standardFieldsPanel:"#standardFields",_fancyFieldsPanel:"#fancyFields",_fieldSettingsPanel:"#fieldSettings",_fieldSettingsLanguageSection:"#fieldSettings fieldset.language:first",_fieldSettingsGeneralSection:"#fieldSettings div.general:first",_formSettingsLanguageSection:"#formSettings fieldset.language:first",_formSettingsGeneralSection:"#formSettings div.general:first",
_languagesSupportIdGeneration:["en"],_dragBoxCss:{opacity:0.6,zIndex:8888,border:"5px solid #cccccc"},_formControls:"#builderPanel fieldset",_draggableClass:"draggable",_dropPlaceHolderClass:"dropPlaceHolder"},_create:function(){this._initBrowserDefaultSettings();this._initBuilderPalette();this._initBuilderPanel()},_initBrowserDefaultSettings:function(){var c=$("html"),a=this.options;a._fontFamily=c.css("fontFamily");a._fontSize=c.css("fontSize");a._color=c.css("color");a._backgroundColor=c.css("backgroundColor");
c=a._fontSize.lastIndexOf("px");if(c>-1)a._fontSize=a._fontSize.substring(0,c)},_initBuilderPalette:function(){$(window).scroll(function(){if($(window).scrollTop()>$(".floatingPanelIdentifier").position({scroll:false}).top){$(".floatingPanel").css("position","fixed");$(".floatingPanel").css("top","0")}if($(window).scrollTop()<=$(".floatingPanelIdentifier").position({scroll:false}).top){$(".floatingPanel").css("position","relative");$(".floatingPanel").css("top",$(".floatingPanelIdentifier").position)}});
$(this.options._paletteTabs).tabs({selected:this.options.tabSelected,disabled:this.options.tabDisabled,select:this._isFieldSettingsTabCanOpen});var c=this.options.fields;c=c.split(",");var a=c.length,b,g,h;for(h=0;h<a;h++){b=$.fb["fb"+$.trim(c[h])].prototype.options;g=$('<a id="'+b._type+'" href="#" class="fbWidget">'+b.name+"</a>");g.button()["fb"+b._type]().appendTo(b.belongsTo);this._initDraggable(g,b._type)}},_initDraggable:function(c,a){c.draggable({cursor:"move",distance:10,helper:function(b){return $(this).data("fb"+
a)._createFbWidget(b).css($.fb.formbuilder.prototype.options._dragBoxCss).css({width:$(".formHeading").css("width")}).addClass($.fb.formbuilder.prototype.options._draggableClass)},drag:function(b,g){var h=$.fb.formbuilder.prototype._getPreviousCtrlHolder(g),e=$.fb.formbuilder.prototype.options;if(h&&h.attr("rel")!=g.helper.attr("rel")){g.helper.attr("rel",h.attr("rel"));$("."+e._dropPlaceHolderClass).remove();$("<div></div>").addClass(e._dropPlaceHolderClass).css("height","30px").insertAfter(h)}else{h=
$("."+$.fb.fbWidget.prototype.options._styleClass+":visible:not(."+e._draggableClass+"):first");h.length&&g.offset.top<h.offset().top&&$("."+e._dropPlaceHolderClass).remove()}},stop:function(){$("."+$.fb.formbuilder.prototype.options._dropPlaceHolderClass).remove()}})},_isFieldSettingsTabCanOpen:function(c,a){if(a.index==1){var b=$.fb.formbuilder.prototype.options,g=true;if($(b._emptyBuilderPanel).is(":visible")){$(b._standardFieldsPanel).qtip({content:"No field was created. Please select standard field or fancy field.",
position:{my:"bottom left",at:"top center"},show:{event:false,ready:true,effect:function(){$(this).show("drop",{direction:"up"})}},hide:{target:$(b._standardFieldsPanel+", "+b._fancyFieldsPanel)},style:{widget:true,classes:"ui-tooltip-shadow ui-tooltip-rounded",tip:true}});g=false}else if($(b._builderForm+" ."+$.fb.fbWidget.prototype.options._selectedClass).length===0){$("."+$.fb.fbWidget.prototype.options._styleClass+":first").qtip({content:"Please select field below to see it's Field Settings.",
position:{my:"bottom center",at:"top center"},show:{event:false,ready:true,effect:function(){$(this).show("drop",{direction:"up"})}},hide:"click",style:{widget:true,classes:"ui-tooltip-shadow ui-tooltip-rounded",tip:true}});g=false}g||$(this).tabs("select",0);return g}},_initBuilderPanel:function(){this._initFormSettings();if(this.options.readOnly){$("input:not(div.buttons input, #id)").attr("disabled",true);$("select:not(#language)").attr("disabled",true);$("textarea").attr("disabled",true)}else{this._initSortableWidgets();
this._initDroppable()}this._initWidgetsEventBinder()},_initDroppable:function(){var c=this.options,a=$(c._formControls);a.droppable({drop:function(b,g){if(g.helper.attr("class").lastIndexOf(c._draggableClass)>-1){$("."+c._dropPlaceHolderClass).remove();var h=g.draggable.data("fb"+g.draggable.attr("id")),e=$.fb.formbuilder.prototype._getPreviousCtrlHolder(g);h=h._createFbWidget(b);if(e){h.insertAfter(e);e=e.next().nextAll(":visible")}else{$(c._emptyBuilderPanel+":visible").hide();e=$("."+$.fb.fbWidget.prototype.options._styleClass+
":visible:not(."+c._draggableClass+")",a);a.prepend(h).sortable("refresh")}h.toggle("slide",{direction:"up"},"slow");if(e.length){$.fb.formbuilder.prototype._getSequence(h).val($.fb.formbuilder.prototype._getSequence(e.first()).val()).change();e.each(function(){$.fb.formbuilder.prototype._increaseSequence($(this))})}}}})},_getPreviousCtrlHolder:function(c){var a,b;$("."+$.fb.fbWidget.prototype.options._styleClass+":visible:not(."+$.fb.formbuilder.prototype.options._draggableClass+")").each(function(){a=
$(this);if(c.offset.top>a.offset().top)b=a;else return false});return b},_initFormSettings:function(){var c=$.fb.fbWidget.prototype,a=this.options,b=$(a._builderPanel),g=$(a._builderForm),h=$(a._formSettingsLanguageSection),e=$(a._formSettingsGeneralSection),f=$.inArray(a.language,a._languages)>-1?a.language:"en",d=$("#language",h).val(f).change(this._languageChange),i,j=this,k=$(".formHeading",b);f=$("#settings",g);if(f.val()==""){i=a.settings[d.val()];for(f=0;f<a._languages.length;f++)a.settings[a._languages[f]].name+=
" "+a.formCounter;k.addClass(i.classes[0]).append("<"+i.heading+' class="heading">'+i.name+"</"+i.heading+">");$("#name",g).val(c._propertyName(a.settings.en.name));j._updateSettings(j)}else{a.settings=$.parseJSON(unescape(f.val()));i=a.settings[d.val()]}f=c._label({label:"Name",name:"form.name"}).append('<input type="text" id="form.name" value="'+i.name+'" />');$("input",f).keyup(function(){var l=$(this).val();if(!a.disabledNameChange&&$.inArray(d.val(),a._languagesSupportIdGeneration)>-1){var p=
c._propertyName(l);$("#name",g).val(p).change()}i.name=l;$(i.heading,k).text(l);j._updateSettings(j)});var m=c._label({label:"Heading",name:"form.heading"}).append('<select> \t\t\t\t<option value="h1">Heading 1</option> \t\t\t\t<option value="h2">Heading 2</option> \t\t\t\t<option value="h3">Heading 3</option> \t\t\t\t<option value="h4">Heading 4</option> \t\t\t\t<option value="h5">Heading 5</option> \t\t\t\t<option value="h6">Heading 6</option> \t\t\t</select>');$("select",m).val(i.heading).attr("id",
"form.heading").change(function(){var l=$(this).val(),p=$(i.heading,k).text();p=$("<"+l+' class="heading">'+p+"</"+l+">");i.styles.fontStyles[0]===0&&p.css("fontWeight","normal");i.styles.fontStyles[1]==1&&p.css("fontStyle","italic");i.styles.fontStyles[2]==1&&p.css("textDecoration","underline");$(i.heading,k).replaceWith(p);i.heading=l;j._updateSettings(j)});var o=c._horizontalAlignment({name:"form.horizontalAlignment",value:i.classes[0]});$("select",o).change(function(){var l=$(this).val();k.removeClass(i.classes[0]).addClass(l);
i.classes[0]=l;j._updateSettings(j)});i.styles.fontFamily=i.styles.fontFamily=="default"?a._fontFamily:i.styles.fontFamily;i.styles.fontSize=i.styles.fontSize=="default"?a._fontSize:i.styles.fontSize;var q=c._fontPanel({fontFamily:i.styles.fontFamily,fontSize:i.styles.fontSize,fontStyles:i.styles.fontStyles,idPrefix:"form.",nofieldset:true});$("input[id$='form.bold']",q).change(function(){if($(this).attr("checked")){$(i.heading,k).css("fontWeight","bold");i.styles.fontStyles[0]=1}else{$(i.heading,
k).css("fontWeight","normal");i.styles.fontStyles[0]=0}j._updateSettings(j)});$("input[id$='form.italic']",q).change(function(){if($(this).attr("checked")){$(i.heading,k).css("fontStyle","italic");i.styles.fontStyles[1]=1}else{$(i.heading,k).css("fontStyle","normal");i.styles.fontStyles[1]=0}j._updateSettings(j)});$("input[id$='form.underline']",q).change(function(){if($(this).attr("checked")){$(i.heading,k).css("textDecoration","underline");i.styles.fontStyles[2]=1}else{$(i.heading,k).css("textDecoration",
"none");i.styles.fontStyles[2]=0}j._updateSettings(j)});$("input[id$='form.fontFamily']",q).change(function(){var l=$(this).val();b.css("fontFamily",l);i.styles.fontFamily=l;j._updateSettings(j)});$("select[id$='form.fontSize']",q).change(function(){var l=$(this).val();b.css("fontSize",l+"px");i.styles.fontSize=l;j._updateSettings(j)});if(a.settings.styles.color=="default")a.settings.styles.color=a._color;if(a.settings.styles.backgroundColor=="default")a.settings.styles.backgroundColor=a._backgroundColor;
var n=c._colorPanel({color:a.settings.styles.color,backgroundColor:a.settings.styles.backgroundColor,idPrefix:"form."});$("input[id$='form.color']",n).change(function(){var l=$(this).data("colorPicker").color;b.css("color","#"+l);a.settings.styles.color=l;j._updateSettings(j)});$("input[id$='form.backgroundColor']",n).change(function(){var l=$(this).data("colorPicker").color;b.css("backgroundColor","#"+l);a.settings.styles.backgroundColor=l;j._updateSettings(j)});h.append(c._oneColumn(f)).append(c._twoColumns(m,
o)).append(q);e.append(n)},_languageChange:function(c){var a=$.fb.fbWidget.prototype._getFbOptions(),b=$("."+$.fb.fbWidget.prototype.options._styleClass+":visible"),g=$(this).val(),h=$("option:selected",this).text(),e=a.settings[g],f=$(".formHeading"),d=$(a._formSettingsLanguageSection),i=$(a._builderPanel),j,k,m,o;$("input[id$='form.name']",d).val(e.name);$("select[id$='form.heading'] option[value='"+e.heading+"']",d).attr("selected","true");var q=$("<"+e.heading+' class="heading">'+e.name+"</"+
e.heading+">").css("fontWeight",e.styles.fontStyles[0]==1?"bold":"normal").css("fontStyle",e.styles.fontStyles[1]==1?"italic":"normal").css("textDecoration",e.styles.fontStyles[2]==1?"underline":"none");$(".heading",f).replaceWith(q);$("input[id$='form.bold']",d).attr("checked",e.styles.fontStyles[0]);$("input[id$='form.italic']",d).attr("checked",e.styles.fontStyles[1]);$("input[id$='form.underline']",d).attr("checked",e.styles.fontStyles[2]);f.removeClass("leftAlign centerAlign rightAlign").addClass(e.classes[0]);
$("select[id$='form.horizontalAlignment'] option[value='"+e.classes[0]+"']",d).attr("selected","true");e.styles.fontFamily=e.styles.fontFamily=="default"?a._fontFamily:e.styles.fontFamily;e.styles.fontSize=e.styles.fontSize=="default"?a._fontSize:e.styles.fontSize;i.css("fontFamily",e.styles.fontFamily);i.css("fontSize",e.styles.fontSize+"px");$("select[id$='form.fontSize']",d).val(e.styles.fontSize);$(".fontPicker",d).fontPicker("fontFamily",e.styles.fontFamily);b.each(function(){var n=$(this);(m=
n.attr("class").indexOf($.fb.fbWidget.prototype.options._selectedClass)>-1)&&$(a._fieldSettingsLanguageSection+" legend").text("Language: "+h);if(!n.data("fbWidget")){var l=n.find("input[id$='fields["+n.attr("rel")+"].settings']");n.data("fbWidget",$.parseJSON(unescape(l.val())))}j=n.data("fbWidget");k=n.find("input[id$='fields["+n.attr("rel")+"].type']").val();$this=$("#"+k).data("fb"+k);o={target:$this,item:n,settings:j[g]};(o.item.selected=m)&&$this._createFieldSettings(c,n);$this._languageChange(c,
o)})},_updateSettings:function(c){$("#settings").val($.toJSON(c.options.settings)).change()},_initWidgetsEventBinder:function(){var c=$("."+$.fb.fbWidget.prototype.options._styleClass);if(c.size()>0){var a,b,g=["name","settings","sequence"];$(this.options._emptyBuilderPanel+":visible").hide();c.each(function(h){a=$(this);b=a.find("input[id$='fields["+h+"].type']").val();a.click($.fb["fb"+b].prototype._createFieldSettings);for(var e=0;e<g.length;e++)a.find("input[id$='fields["+h+"]."+g[e]+"']").change($.fb.fbWidget.prototype._updateStatus)});
this.options.readOnly||c.find(".closeButton").click($.fb.fbWidget.prototype._deleteWidget).mouseover(function(){$("span",this).removeClass("ui-icon-close").addClass("ui-icon-circle-close")}).mouseout(function(){$("span",this).removeClass("ui-icon-circle-close").addClass("ui-icon-close")})}},_initSortableWidgets:function(){var c=$(this.options._formControls);c.sortable({axis:"y",cursor:"move",distance:10,helper:function(a,b){return $(b).clone().css($.fb.formbuilder.prototype.options._dragBoxCss)},
start:function(a,b){var g=$(b.item).prev();if(g.attr("rel")){b.item.prevIndex=g.attr("rel");b.item.originalOffsetTop=g.offset().top}},update:$.fb.formbuilder.prototype._updateSequence});c.disableSelection()},_updateSequence:function(c,a){var b=$(a.item),g;g=a.offset.top>a.item.originalOffsetTop;if(a.item.prevIndex){var h='[rel="'+a.item.prevIndex+'"]';if(g){g=b.prevUntil(h);$.fb.formbuilder.prototype._moveDown(b,g)}else{$.fb.formbuilder.prototype._getSequence(b).val($.fb.formbuilder.prototype._getSequence(b.next()).val()).change();
g=b.nextUntil(h);g.each(function(){$.fb.formbuilder.prototype._increaseSequence($(this))});$.fb.formbuilder.prototype._increaseSequence($(h))}}else{g=b.prevAll();$.fb.formbuilder.prototype._moveDown(b,g)}},_init:function(){this.method1("calling from FormBuilder._init")},destroy:function(){$.Widget.prototype.destroy.call(this)},_moveDown:function(c,a){$.fb.formbuilder.prototype._getSequence(c).val($.fb.formbuilder.prototype._getSequence(c.prev()).val()).change();a.each(function(){$.fb.formbuilder.prototype._decreaseSequence($(this))})},
_getSequence:function(c){return c.find("input[id$='fields["+c.attr("rel")+"].sequence']")},_increaseSequence:function(c){if(c.is(":visible")){c=$.fb.formbuilder.prototype._getSequence(c);c.val(c.val()*1+1);c.change()}},_decreaseSequence:function(c){if(c.is(":visible")){c=$.fb.formbuilder.prototype._getSequence(c);c.val(c.val()-1);c.change()}},method1:function(){}};$.widget("fb.formbuilder",FormBuilder);
var ColorPicker={options:{name:"jquery-color-picker",value:"",ico:"ico.gif",disabledIco:"ico.gif",title:"Pick a colour",inputBG:true,showColorCode:false,speed:500,openTxt:"Open colour picker",type:"basic",width:180,basicColors:["ffffff","ffccc9","ffce93","fffc9e","ffffc7","9aff99","96fffb","cdffff","cbcefb","cfcfcf","fd6864","fe996b","fffe65","fcff2f","67fd9a","38fff8","68fdff","9698ed","c0c0c0","fe0000","f8a102","ffcc67","f8ff00","34ff34","68cbd0","34cdf9","6665cd","9b9b9b","cb0000","f56b00","ffcb2f",
"ffc702","32cb00","00d2cb","3166ff","6434fc","656565","9a0000","ce6301","cd9934","999903","009901","329a9d","3531ff","6200c9","343434","680100","963400","986536","646809","036400","34696d","00009b","303498","000000","330001","643403","663234","343300","013300","003532","010066","340096"],webSafeColors:["000000","000033","000066","000099","0000CC","0000FF","003300","003333","003366","003399","0033CC","0033FF","006600","006633","006666","006699","0066CC","0066FF","009900","009933","009966","009999",
"0099CC","0099FF","00CC00","00CC33","00CC66","00CC99","00CCCC","00CCFF","00FF00","00FF33","00FF66","00FF99","00FFCC","00FFFF","330000","330033","330066","330099","3300CC","3300FF","333300","333333","333366","333399","3333CC","3333FF","336600","336633","336666","336699","3366CC","3366FF","339900","339933","339966","339999","3399CC","3399FF","33CC00","33CC33","33CC66","33CC99","33CCCC","33CCFF","33FF00","33FF33","33FF66","33FF99","33FFCC","33FFFF","660000","660033","660066","660099","6600CC","6600FF",
"663300","663333","663366","663399","6633CC","6633FF","666600","666633","666666","666699","6666CC","6666FF","669900","669933","669966","669999","6699CC","6699FF","66CC00","66CC33","66CC66","66CC99","66CCCC","66CCFF","66FF00","66FF33","66FF66","66FF99","66FFCC","66FFFF","990000","990033","990066","990099","9900CC","9900FF","993300","993333","993366","993399","9933CC","9933FF","996600","996633","996666","996699","9966CC","9966FF","999900","999933","999966","999999","9999CC","9999FF","99CC00","99CC33",
"99CC66","99CC99","99CCCC","99CCFF","99FF00","99FF33","99FF66","99FF99","99FFCC","99FFFF","CC0000","CC0033","CC0066","CC0099","CC00CC","CC00FF","CC3300","CC3333","CC3366","CC3399","CC33CC","CC33FF","CC6600","CC6633","CC6666","CC6699","CC66CC","CC66FF","CC9900","CC9933","CC9966","CC9999","CC99CC","CC99FF","CCCC00","CCCC33","CCCC66","CCCC99","CCCCCC","CCCCFF","CCFF00","CCFF33","CCFF66","CCFF99","CCFFCC","CCFFFF","FF0000","FF0033","FF0066","FF0099","FF00CC","FF00FF","FF3300","FF3333","FF3366","FF3399",
"FF33CC","FF33FF","FF6600","FF6633","FF6666","FF6699","FF66CC","FF66FF","FF9900","FF9933","FF9966","FF9999","FF99CC","FF99FF","FFCC00","FFCC33","FFCC66","FFCC99","FFCCCC","FFCCFF","FFFF00","FFFF33","FFFF66","FFFF99","FFFFCC","FFFFFF"],customColors:[],disabled:false},_init:function(){this.element.append('<input type="text" id="'+this.options.name+'" name="'+this.options.name+'" /> \t\t\t\t<a class="floatLeft" href="#" rel="'+this.options.name+'"> \t\t\t\t<img border="0" src="'+(this.options.disabled?
this.options.disabledIco:this.options.ico)+'" alt="'+this.options.openTxt+'"/></a>');var c=$("input",this.element).attr("readonly",true),a=this.element.data("colorPicker"),b="colorpicker_"+this.options.type;a.options.showColorCode?c.val(this.options.value):c.attr("disabled","true");c.data("colorPicker",{color:this.options.value});var g=$("#"+b);if(g.length==0&&!this.options.disabled){for(var h="",e=this.options[this.options.type+"Colors"],f,d=0;d<e.length;d++){f=e[d];if(f!="")h+='<li><a href="#" title="'+
f+'" rel="'+f+'" style="background: #'+f+"; color: "+this._hexInvert(f)+';">'+f+"</a></li>"}g=$('<div id="'+b+'" class="colorPicker">'+(this.options.title?"<h2>"+this.options.title+"</h2>":"")+"<ul>"+h+"</ul></div>").appendTo(document.body).hide();$(document.body).click(function(j){$(j.target).is(".colorPicker")||$(j.target).parents(".colorPicker").length||g.hide(a.options.speed)})}if(this.options.inputBG){b=this.options.value;if(b.length==6)b="#"+b;c.css({background:b,color:"#"+this._hexInvert(b)})}if(!this.options.disabled){var i=
$("a",this.element);i.click(function(){var j=i.offset();g.css({position:"absolute",left:j.left+"px",top:j.top+"px",width:a.options.width+"px"}).show(a.options.speed).attr("rel",i.attr("rel"));return false})}$("a",g).click(function(j){var k=$("input[id$='"+g.attr("rel")+"']"),m=$(this).attr("rel"),o=k.parent().data("colorPicker").options;o.showColorCode&&k.val(m);k.data("colorPicker",{color:m});o.inputBG&&k.css({background:"#"+m,color:"#"+a._hexInvert(m)});k.change();g.hide(a.options.speed);j.stopImmediatePropagation();
return false})},_hexInvert:function(c){var a=c.substr(0,2),b=c.substr(2,2);c=c.substr(4,2);return 0.212671*a+0.71516*b+0.072169*c<0.5?"ffffff":"000000"}};$.widget("fb.colorPicker",ColorPicker);
var FontPicker={fonts:Array("Arial,Arial,Helvetica,sans-serif","Arial Black,Arial Black,Gadget,sans-serif","Comic Sans MS,Comic Sans MS,cursive","Courier New,Courier New,Courier,monospace","Georgia,Georgia,serif","Impact,Charcoal,sans-serif","Lucida Console,Monaco,monospace","Lucida Sans Unicode,Lucida Grande,sans-serif","Palatino Linotype,Book Antiqua,Palatino,serif","Tahoma,Geneva,sans-serif","Times New Roman,Times,serif","Trebuchet MS,Helvetica,sans-serif","Verdana,Geneva,sans-serif"),options:{defaultFont:"Tahoma",
id:"fontbox",name:"fontPickerInput",selClass:"fontPicker",fontclass:"singlefont",speed:100,hoverColor:"#efefff",bgColor:"#ffffee",disabled:false},_init:function(){var c=this.options,a=$("#"+c.id);this.element.parent().append('<input type="hidden" id="'+c.name+'" />');if(!a.length&&!c.disabled){a=$('<div id="'+c.id+'" ></div>').appendTo(document.body).hide();$.each(this.fonts,function(b,g){a.append('<div class="singlefont" onmouseover="this.style.backgroundColor=\''+c.hoverColor+"'\" onmouseout=\"this.style.backgroundColor='"+
c.bgColor+'\'" style="font-family: '+g+';" value="'+g+'"> '+g.split(",")[0]+"</div>")});$(document.body).click(function(b){$(b.target).is("."+c.selClass)||$(b.target).is("#"+c.id)||a.slideUp(c.speed)})}c.disabled||this.element.click(function(){if(a.is(":hidden")){var b=$(this);a.css({position:"absolute",left:b.offset().left+"px",top:b.offset().top+b.height()+3+"px"}).attr("rel",b.attr("rel"));a.slideDown(c.speed)}else a.slideUp(c.speed)});c.defaultFont.length&&this.fontFamily(c.defaultFont);$("."+
c.fontclass).click(function(b){var g=$(this),h=$("input[id$='"+g.parent().attr("rel")+"']"),e=g.attr("value");h.prev().text(g.text()).css("fontFamily",e);h.val(e).change();a.slideUp(c.speed);b.stopImmediatePropagation()})},fontFamily:function(c){c=c.replace(/'/gi,"");this.element.text(c.split(",",1)[0]).css("fontFamily",c);$("input",this.element.parent()).val(c)}};$.widget("fb.fontPicker",FontPicker);
var FbWidget={options:{_styleClass:"ctrlHolder",_selectedClass:"ctrlHolderSelected"},_create:function(){},_init:function(){this.element.click(this._createFbWidget)},destroy:function(){this.element.button("destroy");$.Widget.prototype.destroy.call(this)},_getFbOptions:function(){return $($.fb.formbuilder.prototype.options._id).formbuilder("option")},_getFbLocalizedSettings:function(){return $($.fb.formbuilder.prototype.options._id).formbuilder("option").settings[$("#language").val()]},_createField:function(c,
a,b,g){var h=$.fb.formbuilder.prototype.options,e=$("#builderForm div.ctrlHolder").size();$('<a class="ui-corner-all closeButton" href="#"><span class="ui-icon ui-icon-close">delete this widget</span></a>').prependTo(a).click($.fb.fbWidget.prototype._deleteWidget).mouseover(function(){$("span",this).removeClass("ui-icon-close").addClass("ui-icon-circle-close")}).mouseout(function(){$("span",this).removeClass("ui-icon-circle-close").addClass("ui-icon-close")});a.attr("rel",e);a.append($.fb.fbWidget.prototype._createFieldProperties(c,
b,g,e));$(h._emptyBuilderPanel+":visible").hide()},_propertyName:function(c){c=c.replace(/ /gi,"");return c=c.charAt(0).toLowerCase()+c.substring(1)},_deleteWidget:function(c){var a=$(c.target).parent().parent(),b=a.attr("rel"),g=$.fb.fbWidget.prototype.options,h=$.fb.formbuilder.prototype.options;if(a.find("input[id$='fields["+b+"].id']").val()=="null")a.remove();else{a.find("input[id$='fields["+b+"].status']").val("D");a.hide()}b=$("."+g._styleClass+":visible");a.attr("class").indexOf(g._selectedClass)>
-1&&$(h._paletteTabs).tabs("select",0);b.size()===0&&$(h._emptyBuilderPanel).show();c.stopPropagation()},_createFieldProperties:function(c,a,b,g){var h="fields["+g+"].";c=$('<div class="fieldProperties"> \t\t<input type="hidden" id="'+h+'id" name="'+h+'id" value="null" /> \t\t<input type="hidden" id="'+h+'name" name="'+h+'name" value="'+c+'" /> \t\t<input type="hidden" id="'+h+'type" name="'+h+'type" value="'+a._type+'" /> \t\t<input type="hidden" id="'+h+'settings" name="'+h+'settings" /> \t\t<input type="hidden" id="'+
h+'sequence" name="'+h+'sequence" value="'+g+'" /> \t\t<input type="hidden" id="'+h+'status" name="'+h+'status" /> \t\t</div>');c.find("input[id$='"+h+"settings']").val($.toJSON(b));return c},_updateStatus:function(c){$widget=$(c.target);$widget.parent().find("input:first").val()!="null"&&$widget.parent().find("input:last").val("U")},_createFbWidget:function(c){var a;if(this.options)a=this;else{a="fb"+$(this).fbWidget("option","_type");a=$(this).data(a)}for(var b=jQuery.extend(true,{},a.options.settings),
g=a._getCounter(a),h=a.options._languages,e=0;e<h.length;e++)b[h[e]][a.options._counterField]+=" "+g;h=$('<div class="'+a.options._styleClass+'"></div>').hide();h.data("fbWidget",b);e={target:a,item:h,settings:b[$("#language").val()],_settings:b};e=a._getWidget(c,e);h.append(e);if(c.type=="click"||c.type=="drop"){g=a._propertyName(a.options._type+g);e.click(a._createFieldSettings);a._createField(g,h,a.options,b);if(c.type=="click"){$($.fb.formbuilder.prototype.options._formControls).append(h).sortable("refresh");
h.toggle("slide",{direction:"up"},"slow");a._scroll(c);c.preventDefault()}else return h}else return h.show()},_scroll:function(){var c=$($.fb.formbuilder.prototype.options._builderPanel),a=c.css("minHeight");c=c.css("height");a=a.substring(0,a.lastIndexOf("px"))*1;c=c.substring(0,c.lastIndexOf("px"))*1;if(c>a){a=c-a;$("html, body").stop().animate({scrollTop:a},1500,"easeInOutExpo")}},_createFieldSettings:function(c,a){a||(a=$(this));var b=$.fb.fbWidget.prototype.options._selectedClass;a=a.attr("class").indexOf($.fb.fbWidget.prototype.options._styleClass)>
-1?a:a.parent();a.parent().find("."+b).removeClass(b);a.addClass(b);b=a.find("input[id$='fields["+a.attr("rel")+"].type']").val();var g=$("#"+b).data("fb"+b);b=g._getFbOptions();if(!a.data("fbWidget")){var h=a.find("input[id$='fields["+a.attr("rel")+"].settings']");a.data("fbWidget",$.parseJSON(unescape(h.val())))}h=a.data("fbWidget");var e=$(b._fieldSettingsLanguageSection),f=$("#language");$("legend",e).text("Language: "+f.find("option:selected").text());f={target:g,item:a,settings:h[f.val()]};
f=g._getFieldSettingsLanguageSection(c,f);e.children(":not(legend)").remove();for(var d=0;d<f.length;d++)e.append(f[d]);f=g._getFieldSettingsGeneralSection(c,{target:g,item:a,settings:h});g=$(b._fieldSettingsGeneralSection);g.children().remove();for(d=0;d<f.length;d++)g.append(f[d]);if(b.readOnly){var i=$(b._fieldSettingsPanel);$("input",i).attr("disabled",true);$("select",i).attr("disabled",true);$("textarea",i).attr("disabled",true)}if(c.type=="click"){$(b._paletteTabs).tabs("select",1);$("input:first",
i).select()}},_getCounter:function(c){var a=$("."+c.options._styleClass+":visible:not(."+this._getFbOptions()._draggableClass+")"),b=1;if(a.size()>0){var g,h,e,f=0,d=c._propertyName(c.options._type);a.each(function(){g=$(this);h=g.attr("rel");e=g.find("input[id$='fields["+h+"].name']").val();if(e.indexOf(d)>-1){f=e.substring(d.length)*1;if(f>b)b=f}});f>0&&b++}return b},_updateSettings:function(c){var a=c.data("fbWidget");c.find("input[id$='fields["+c.attr("rel")+"].settings']").val($.toJSON(a)).change()},
_updateName:function(c,a){var b=this._getFbOptions(),g=b.disabledNameChange,h=c.attr("rel");if(g)g=c.find("input[id$='fields["+h+"].id']").val()!="null";if(!g&&$.inArray($("#language").val(),b._languagesSupportIdGeneration)>-1){b=this._propertyName(a);c.find("input[id$='fields["+h+"].name']").val(b).change()}},_threeColumns:function(c,a,b){return $('<div class="threeCols"></div>').append(c.addClass("col1")).append(a.addClass("col2")).append(b.addClass("col3"))},_twoColumns:function(c,a){return $('<div class="twoCols"></div>').append(c.addClass("labelOnTop col1 noPaddingBottom")).append(a.addClass("labelOnTop col2"))},
_oneColumn:function(c){return c.addClass("clear labelOnTop")},_help:function(c){var a;if(c.description){a=$('<span>&nbsp;(<a href="#" title="'+c.description+'">?</a>)</span>');c=$("a",a);c.qtip({content:c.attr("title"),position:{my:"bottom left",at:"top center"},show:{event:"click",effect:function(){$(this).show("drop",{direction:"up"})}},hide:"mouseout",style:{widget:true,classes:"ui-tooltip-shadow ui-tooltip-rounded",tip:true}})}return a},_label:function(c){var a=$('<div><label for="'+c.name+'">'+
c.label+"</label></div>").append(this._help(c));c.nobreak||a.append("<br />");return a},_horizontalAlignment:function(c){c=$.extend({},c);c.label=c.label?c.label:"Horizontal Align";var a=this._label(c).append('<select> \t\t\t<option value="leftAlign">left</option> \t\t\t<option value="centerAlign">center</option> \t\t\t<option value="rightAlign">right</option> \t\t</select>');$("select",a).val(c.value).attr("id",c.name);return a},_verticalAlignment:function(c){c=$.extend({},c);c.label=c.label?c.label:
"Vertical Align";var a=this._label(c).append('<select> \t\t\t\t<option value="topAlign">top</option> \t\t\t\t<option value="middleAlign">middle</option> \t\t\t\t<option value="bottomAlign">bottom</option> \t\t\t</select></div>');$("select",a).val(c.value).attr("id",c.name);return a},_name:function(c){var a=c.attr("rel"),b=$('<label for="field.name">Name (?)</label><br/>  \t\t\t\t  <input type="text" id="field.name" />');$("input[id$='field.name']",b).val(c.find("input[id$='fields["+a+"].name']").val()).keyup(function(g){c.find("input[id$='fields["+
a+"].name']").val($(g.target).val()).change()});return b},_colorPicker:function(c){var a;a=c.label?this._label(c):$("<div></div>");!c.type||c.type=="basic"?a.colorPicker({name:c.name,value:c.value,ico:"../images/jquery.colourPicker.gif",disabledIco:"../../images/jquery.colourPicker.disabled.gif",title:"Basic Colors",disabled:this._getFbOptions().readOnly}):a.colorPicker({name:name,value:value,ico:"../images/jquery.colourPicker.gif",disabledIco:"../../images/jquery.colourPicker.disabled.gif",title:"Web Safe Colors",
type:"webSafe",width:360,disabled:this._getFbOptions().readOnly});return a},_fontPicker:function(c){c=$.extend({},c);c.value=c.value!="default"?c.value:this._getFbOptions()._fontFamily;if(!c.label)c.label="Font";var a=this._label(c).append('<div class="fontPicker" rel="'+c.name+'"></div>');$(".fontPicker",a).fontPicker({name:c.name,defaultFont:c.value,disabled:this._getFbOptions().readOnly});return a},_fontSize:function(c){c.nobreak=true;var a=this._label(c).append('&nbsp;<select> \t\t    <option value="9">9</option> \t\t    <option value="10">10</option> \t\t    <option value="11">11</option> \t\t    <option value="12">12</option> \t\t    <option value="13">13</option> \t\t    <option value="14">14</option> \t\t    <option value="15">15</option> \t\t    <option value="16">16</option> \t\t    <option value="17">17</option> \t\t    <option value="18">18</option> \t\t    <option value="20">20</option> \t\t    <option value="22">22</option> \t\t    <option value="24">24</option> \t\t    <option value="28">28</option> \t\t    <option value="32">32</option> \t\t  </select>'),
b=$("select",a);c.value=="default"?b.val(this._getFbOptions().settings.styles.fontSize):b.val(c.value);b.attr("id",c.name);return a},_fontStyles:function(c){var a=c.names;c=c.checked;var b=$('<div> \t\t  <input type="checkbox" id="'+a[0]+'" />&nbsp;Bold<br /> \t    <input type="checkbox" id="'+a[1]+'" />&nbsp;Italic<br /> \t    <input type="checkbox" id="'+a[2]+'" />&nbsp;Underline \t  </div>');if(c)for(var g=0;g<c.length;g++)$("input[id$='"+a[g]+"']",b).attr("checked",c[g]);return b},_twoRowsOneRow:function(c,
a,b){var g=$('<div class="twoRowsOneRow"> \t\t\t    <div class="row1col1"> \t\t\t      <div class="row2col1"> \t\t\t      </div> \t\t\t    </div> \t\t\t    <div class="row1col2"> \t\t\t    </div> \t\t\t  </div>');$(".row1col1",g).prepend(c);$(".row2col1",g).append(a);$(".row1col2",g).append(b);return g},_fieldset:function(c){return $("<fieldset><legend>"+c.text+"</legend></fieldset>")},_fontPanel:function(c){var a=c.idPrefix?c.idPrefix:"",b=[a+"bold",a+"italic",a+"underline"];a=this._twoRowsOneRow(this._fontPicker({name:a+
"fontFamily",value:c.fontFamily}),this._fontSize({label:"Size",name:a+"fontSize",value:c.fontSize}),this._fontStyles({names:b,checked:c.fontStyles}).css("paddingLeft","2em"));return c.nofieldset?a:this._fieldset({text:"Fonts"}).append(a)},_colorPanel:function(c){c=$.extend({},c);c.idPrefix=c.idPrefix?c.idPrefix:"";if(c.color=="default")c.color=this._getFbOptions().settings.styles.color;if(c.backgroundColor=="default")c.backgroundColor=this._getFbOptions().settings.styles.backgroundColor;c=this._fieldset({text:"Colors"}).append(this._twoColumns(this._colorPicker({label:"Text",
name:c.idPrefix+"color",value:c.color}),this._colorPicker({label:"Background",name:c.idPrefix+"backgroundColor",value:c.backgroundColor})));c.find(".2cols .col2").addClass("noPaddingBottom");c.find("input:first").addClass("floatClearLeft");return c},_labelValueDescriptionColorPanel:function(c){c=$.extend({},c);var a=this._getFbOptions().settings.styles;if(c.label.color=="default")c.label.color=a.color;if(c.label.backgroundColor=="default")c.label.backgroundColor=a.backgroundColor;if(c.description.color==
"default")c.description.color=a.color;if(c.description.backgroundColor=="default")c.description.backgroundColor=a.backgroundColor;c=this._fieldset({text:"Colors"}).append(this._threeColumns($("<div></div>"),$("<div>Text</div>"),$("<div>Background</div>")).css("paddingBottom","2px")).append(this._threeColumns($("<div>Label</div>"),this._colorPicker({name:"field.label.color",value:c.label.color}),this._colorPicker({name:"field.label.backgroundColor",value:c.label.backgroundColor}))).append(this._threeColumns($("<div>Value</div>"),
this._colorPicker({name:"field.value.color",value:c.value.color}),this._colorPicker({name:"field.value.backgroundColor",value:c.value.backgroundColor}))).append(this._threeColumns($("<div>Description</div>"),this._colorPicker({name:"field.description.color",value:c.description.color}),this._colorPicker({name:"field.description.backgroundColor",value:c.description.backgroundColor})));c.css("paddingTop","0.5em");$("input",c).addClass("floatClearLeft");$(".col1",c).css("verticalAlign","top");return c},
_getWidget:function(){},_getFieldSettingsLanguageSection:function(){},_getFieldSettingsGeneralSection:function(){},_languageChange:function(){}};$.widget("fb.fbWidget",FbWidget);
var FbPlainText=$.extend({},$.fb.fbWidget.prototype,{options:{name:"Plain Text",belongsTo:$.fb.formbuilder.prototype.options._fancyFieldsPanel,_type:"PlainText",_html:'<div class="PlainText"></div>',_counterField:"text",_languages:["en","zh_CN"],settings:{en:{text:"Plain Text",classes:["leftAlign","topAlign"],styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{text:"\u65e0\u683c\ufffd?\u6587\u5b57",classes:["rightAlign","middleAlign"],styles:{fontFamily:"default",fontSize:"default",
fontStyles:[0,0,0]}},styles:{color:"default",backgroundColor:"default"}}},_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){a.item.addClass(a.settings.classes[1]);return $(a.target.options._html).text(a.settings.text).addClass(a.settings.classes[0])},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Text",name:"field.text",description:"Text entered below will display in the form."}).append('<input type="text" id="field.text" />');
$("input",b).val(a.settings.text).keyup(function(){var d=$(this).val();a.item.find("div.PlainText").text(d);a.settings.text=d;a.target._updateSettings(a.item)});var g=a.target._verticalAlignment({name:"field.verticalAlignment",value:a.settings.classes[1]}).change(function(){var d=$("option:selected",this).val();a.item.removeClass(a.settings.classes[1]).addClass(d);a.settings.classes[1]=d;a.target._updateSettings(a.item)}),h=a.target._horizontalAlignment({name:"field.horizontalAlignment",value:a.settings.classes[0]}).change(function(){var d=
a.item.find("div.PlainText"),i=$("option:selected",this).val();d.removeClass(a.settings.classes[0]).addClass(i);a.settings.classes[0]=i;a.target._updateSettings(a.item)}),e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){var d=a.item.find(".PlainText");
if($(this).attr("checked")){d.css("fontWeight","bold");e.fontStyles[0]=1}else{d.css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){var d=a.item.find(".PlainText");if($(this).attr("checked")){d.css("fontStyle","italic");e.fontStyles[1]=1}else{d.css("fontStyle","normal");e.fontStyles[1]=0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){var d=a.item.find(".PlainText");if($(this).attr("checked")){d.css("textDecoration",
"underline");e.fontStyles[2]=1}else{d.css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=$(this).val();a.item.find(".PlainText").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find(".PlainText").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});return[a.target._oneColumn(b),a.target._twoColumns(h,
g),f]},_getFieldSettingsGeneralSection:function(c,a){var b=a.settings.styles,g=a.target._getFbOptions().settings.styles;g=a.target._colorPanel({color:b.color!="default"?b.color:g.color,backgroundColor:b.backgroundColor!="default"?b.backgroundColor:g.backgroundColor,idPrefix:"field."});$("input[id$='field.color']",g).change(function(){var h=$(this).data("colorPicker").color;a.item.css("color","#"+h);b.color=h;a.target._updateSettings(a.item)});$("input[id$='field.backgroundColor']",g).change(function(){var h=
$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+h);b.backgroundColor=h;a.target._updateSettings(a.item)});return[g]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;a.item.find(".PlainText").text(a.settings.text).removeClass("leftAlign centerAlign rightAlign").addClass(a.settings.classes[0]);a.item.css("fontWeight",b.fontStyles[0]==
1?"bold":"normal").css("fontStyle",b.fontStyles[1]==1?"italic":"normal").css("textDecoration",b.fontStyles[2]==1?"underline":"none").css("fontFamily",h).css("fontSize",g+"px").removeClass("topAlign middleAlign bottomAlign").addClass(a.settings.classes[1])}});$.widget("fb.fbPlainText",FbPlainText);
var FbSingleLineText=$.extend({},$.fb.fbWidget.prototype,{options:{name:'<span style="position:relative;font-size:11px"><img src="../images/abc.bmp" style="position:absolute;left:-16px;z-index:2;width:20px" >&nbspSingle Line Text</span>',belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"SingleLineText",_html:'<div><label><em></em><span></span></label> \t\t      <input type="text" class="textInput" /> \t        <p class="formHint"></p></div>',_counterField:"label",_languages:["en",
"zh_CN"],settings:{en:{label:"Single Line Text",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:true,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",backgroundColor:"default"}}}},
_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){var b=$(a.target.options._html);$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Label",name:"field.label"}).append('<input type="text" id="field.label" />');
$("input",b).val(a.settings.label).keyup(function(){var d=$(this).val();a.item.find("label span").text(d);a.settings.label=d;a.target._updateSettings(a.item);a.target._updateName(a.item,d)});var g=a.target._label({label:"Value",name:"field.value"}).append('<input type="text" id="field.value" />');$("input",g).val(a.settings.value).keyup(function(){var d=$(this).val();a.item.find(".textInput").val(d);a.settings.value=d;a.target._updateSettings(a.item)});var h=a.target._label({label:"Description",name:"field.description"}).append('<textarea id="field.description" rows="2"></textarea>');
$("textarea",h).val(a.settings.description).keyup(function(){var d=$(this).val();a.item.find(".formHint").text(d);a.settings.description=d;a.target._updateSettings(a.item)});var e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight",
"bold");a.item.find(".textInput").css("fontWeight","bold");e.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle","italic");a.item.find(".textInput").css("fontStyle","italic");e.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle",
"normal");e.fontStyles[1]=0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");e.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration","none");a.item.find(".textInput").css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=
$(this).val();a.item.css("fontFamily",d);a.item.find(".textInput").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find("label").css("fontSize",d+"px");a.item.find(".textInput").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});return[a.target._twoColumns(b,g),a.target._oneColumn(h),f]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),
g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");
$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected","true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=
e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});
$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor","#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color",
"#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;
var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});
$.widget("fb.fbSingleLineText",FbSingleLineText);
var FbMultiLineText=$.extend({},$.fb.fbWidget.prototype,{options:{name:'<span style="position:relative;font-size:11px"><img src="../images/para.bmp" style="position:absolute;left:-16px;z-index:2;width:20px" >&nbspParagraph Text</span>',belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"MultiLineText",_html:'<div><label><em></em><span></span></label> \t\t      <textarea row="4" cols="20" class="textInput" /> \t        <p class="formHint"></p></div>',_counterField:"label",_languages:["en",
"zh_CN"],settings:{en:{label:"Multi Line Text",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:true,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",backgroundColor:"default"}}}},
_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){var b=$(a.target.options._html);$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Label",name:"field.label"}).append('<input type="text" id="field.label" />');
$("input",b).val(a.settings.label).keyup(function(){var d=$(this).val();a.item.find("label span").text(d);a.settings.label=d;a.target._updateSettings(a.item);a.target._updateName(a.item,d)});var g=a.target._label({label:"Value",name:"field.value"}).append('<input type="text" id="field.value" />');$("input",g).val(a.settings.value).keyup(function(){var d=$(this).val();a.item.find(".textInput").val(d);a.settings.value=d;a.target._updateSettings(a.item)});var h=a.target._label({label:"Description",name:"field.description"}).append('<textarea id="field.description" rows="2"></textarea>');
$("textarea",h).val(a.settings.description).keyup(function(){var d=$(this).val();a.item.find(".formHint").text(d);a.settings.description=d;a.target._updateSettings(a.item)});var e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight",
"bold");a.item.find(".textInput").css("fontWeight","bold");e.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle","italic");a.item.find(".textInput").css("fontStyle","italic");e.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle",
"normal");e.fontStyles[1]=0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");e.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration","none");a.item.find(".textInput").css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=
$(this).val();a.item.css("fontFamily",d);a.item.find(".textInput").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find("label").css("fontSize",d+"px");a.item.find(".textInput").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});return[a.target._twoColumns(b,g),a.target._oneColumn(h),f]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),
g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");
$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected","true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=
e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});
$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor","#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color",
"#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;
var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});
$.widget("fb.fbMultiLineText",FbMultiLineText);
var dropDown1="dropdown1",FbDropDown=$.extend({},$.fb.fbWidget.prototype,{options:{name:"Select",belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"dropdown",_html:'<div><label><em></em><span></span></label> \t\t      <select id="dropdown1">\t\t\t</select> \t        <p class="formHint"></p></div>',_counterField:"label",_languages:["en","zh_CN"],settings:{en:{label:"Dropdown Text",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",
value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:true,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",backgroundColor:"default"}}}},_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){dropDown="dropdown1";var b=$(a.target.options._html);
$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Label",name:"field.label"}).append('<input type="text" id="field.label" />');$("input",b).val(a.settings.label).keyup(function(){var d=$(this).val();a.item.find("label span").text(d);a.settings.label=d;a.target._updateSettings(a.item);a.target._updateName(a.item,
d)});var g=a.target._label({label:"Value",name:"field.value"}).append('<input type="text" id="field.value" />');$("input",g).val(a.settings.value).keyup(function(){for(var d=$(this).val(),i=d.length,j=d.split(","),k="",m=0;m<j.length-1;m++)k+="<option>"+j[m]+"</option>";$("#"+dropDown1).html(k);$("#"+dropDown1).attr("id",i);dropDown1=i;a.item.find(".textInput").val(d);a.settings.value=d;a.target._updateSettings(a.item)});var h=a.target._label({label:"Description",name:"field.description"}).append('<textarea id="field.description" rows="2"></textarea>');
$("textarea",h).val(a.settings.description).keyup(function(){var d=$(this).val();a.item.find(".formHint").text(d);a.settings.description=d;a.target._updateSettings(a.item)});var e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight",
"bold");a.item.find(".textInput").css("fontWeight","bold");e.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle","italic");a.item.find(".textInput").css("fontStyle","italic");e.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle",
"normal");e.fontStyles[1]=0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");e.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration","none");a.item.find(".textInput").css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=
$(this).val();a.item.css("fontFamily",d);a.item.find(".textInput").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find("label").css("fontSize",d+"px");a.item.find(".textInput").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});return[a.target._twoColumns(b,g),a.target._oneColumn(h),f]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),
g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");
$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected","true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=
e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});
$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor","#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color",
"#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;
var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});
$.widget("fb.fbdropdown",FbDropDown);
var radioId="checkbox",GroupButton=$.extend({},$.fb.fbWidget.prototype,{options:{name:'<span style="position:relative;font-size:11px"><img src="../images/radio.bmp" style="position:absolute;left:-16px;z-index:2;width:20px" >&nbspMultiple Choice</span>',belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"GroupButton",_html:'<div>\t        <input type="radio" id="checkbox"><label><span style="position:absolute;top:20px;left:50px"></span></label></div>',_counterField:"label",_languages:["en",
"zh_CN"],settings:{en:{label:"Radio Button",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:true,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",backgroundColor:"default"}}}},
_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){radioId="checkbox";var b=$(a.target.options._html);$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Label",name:"field.label"}).append('<input type="text" id="field.label" />');
$("input",b).val(a.settings.label).keyup(function(){var d=$(this).val();a.item.find("label span").text(d);a.settings.label=d;a.target._updateSettings(a.item);a.target._updateName(a.item,d)});var g=a.target._label({label:"Value",name:"field.value"}).append('<input type="text" id="field.value" />');$("input",g).val(a.settings.value).keyup(function(){var d=$(this).val();$("#"+radioId).attr("name",d);$("#"+radioId).attr("id","radio"+d);radioId="radio"+d;a.settings.value=d;a.target._updateSettings(a.item)});
var h=a.target._label({label:"Description",name:"field.description"}).append('<textarea id="field.description" rows="2"></textarea>');$("textarea",h).val(a.settings.description).keyup(function(){var d=$(this).val();a.item.find(".formHint").text(d);a.settings.description=d;a.target._updateSettings(a.item)});var e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:
f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight","bold");a.item.find(".textInput").css("fontWeight","bold");e.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle",
"italic");a.item.find(".textInput").css("fontStyle","italic");e.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle","normal");e.fontStyles[1]=0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");e.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration",
"none");a.item.find(".textInput").css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=$(this).val();a.item.css("fontFamily",d);a.item.find(".textInput").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find("label").css("fontSize",d+"px");a.item.find(".textInput").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});
return[a.target._twoColumns(b,g),a.target._oneColumn(h),f]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),
h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected",
"true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});
$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor",
"#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color","#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});
return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",
g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});$.widget("fb.fbGroupButton",GroupButton);function setLabel(c){$("#"+c+"s").text($("#"+c).val());$("#"+c+"t").prop("name",$("#"+c).val())}
function addwidget(c){var a=(new Date).getTime();$("#w"+c).after('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div style="display:block" id="w'+a+'"><input type="checkbox" id="'+a+'t" style="width:10px;margin-right:10px;"><input type="Text" style="width:160px" value="Enter your Choice" id="'+a+'"  onKeyUp=setLabel("'+a+'")><a href="#" onclick=addwidget("'+a+'")><img src="../images/add.png" style="width:20px;"></a><a href="#" onclick=removewidget("'+a+'")><img src="../images/images.png" style="width:20px;"></a></div> ');
$("#"+c+"d").after('<div id="'+a+'d"><input type="checkbox" value="" name="" id="'+a+'t"><div id="'+a+'l" style="display:inline"><span id="'+a+'s">Enter your Choice Choice</span></div><br/><br/></div> ')}function removewidget(c){$("#w"+c).html("");$("#"+c+"d").html("")}
var checkBoxid="checkBox",FbCheckBox=$.extend({},$.fb.fbWidget.prototype,{options:{name:'<span style="position:relative;font-size:11px"><img src="../images/check.bmp" style="position:absolute;left:-16px;z-index:2;width:15px" >&nbsp&nbsp&nbspCheckBoxes</span>',belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"CheckBox",_html:'<div><label><span></span></label> \t\t         <div id="FirstChoiced"><input type="checkbox" value="" name="FirstChoice" id="FirstChoicet"><div id="FirstChoicel" style="display:inline"><span id="FirstChoices">First Choice</span></div><br/><br/></div> \t\t\t\t<div id="SecondChoiced"><input type="checkbox" value="" name="SecondChoice" id="SecondChoicet"><div id="SecondChoicel" style="display:inline"><span id="SecondChoices">Second Choice</span></div><br/><br/></div>\t\t\t\t<div id="ThirdChoiced"><input type="checkbox" value="" name="ThirdChoice" id="ThirdChoicet"><div id="ThirdChoicel" style="display:inline"><span id="ThirdChoices">Third Choice</span></div><br/><br/></div>\t\t\t\t</div>\t       ',
_counterField:"label",_languages:["en","zh_CN"],settings:{en:{label:"Checkbox",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:false,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",
backgroundColor:"default"}}}},_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){checkBoxid="checkBox";var b=$(a.target.options._html);$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Field Label (?)",
name:"field.label"}).append('<textarea rows="3" cols="20" id="field.label" />');$("textarea",b).val(a.settings.label).keyup(function(){var f=$(this).val();a.item.find("label span").text(f);a.settings.label=f;a.target._updateSettings(a.item);a.target._updateName(a.item,f)});var g=$('<div> \t\t\t\t<div style="display:inline;" id="wFirstChoice"><input type="checkbox" id="FirstChoicet" style="width:10px;margin-right:10px;"><input type="Text" style="width:165px" value="First Choice" id="FirstChoice"   onKeyUp=setLabel("FirstChoice")><a href="#" onclick=addwidget("FirstChoice")><img src="../images/add.png" style="width:20px;"></a><a href="#" onclick=removewidget("FirstChoice")><img src="../images/images.png" style="width:20px;"></a></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\t\t\t\t<div style="display:inline;" id="wSecondChoice"><input type="checkbox" id="SecondChoicet" style="width:10px;margin-right:10px;"><input type="Text" style="width:160px" value="Second Choice" id="SecondChoice"   onKeyUp=setLabel("SecondChoice")><a href="#" onclick=addwidget("SecondChoice")><img src="../images/add.png" style="width:20px;"></a><a href="#" onclick=removewidget("SecondChoice")><img src="../images/images.png" style="width:20px;"></a></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\t\t\t\t<div style="display:block" id="wThirdChoice"><input type="checkbox" id="ThirdChoicet" style="width:10px;margin-right:10px;"><input type="Text" style="width:160px" value="Third Choice" id="ThirdChoice"   onKeyUp=setLabel("ThirdChoice")><a href="#" onclick=addwidget("ThirdChoice")><img src="../images/add.png" style="width:20px;"></a><a href="#" onclick=removewidget("ThirdChoice")><img src="../images/images.png" style="width:20px;"></a></div> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\t\t\t\t</div>');
g=a.target._fieldset({text:"Choices"}).append(a.target._oneColumn(g));var h=a.settings.styles,e=a.target._getFbLocalizedSettings().styles;e=a.target._fontPanel({fontFamily:h.fontFamily!="default"?h.fontFamily:e.fontFamily,fontSize:h.fontSize!="default"?h.fontSize:e.fontSize,fontStyles:h.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",e).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight","bold");a.item.find(".textInput").css("fontWeight",
"bold");h.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");h.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",e).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle","italic");a.item.find(".textInput").css("fontStyle","italic");h.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle","normal");h.fontStyles[1]=
0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",e).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");h.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration","none");a.item.find(".textInput").css("textDecoration","none");h.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",e).change(function(){var f=$(this).val();a.item.css("fontFamily",
f);a.item.find(".textInput").css("fontFamily",f);h.fontFamily=f;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",e).change(function(){var f=$(this).val();a.item.find("label").css("fontSize",f+"px");a.item.find(".textInput").css("fontSize",f+"px");h.fontSize=f;a.target._updateSettings(a.item)});return[a.target._oneColumn(b),g,e]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),
h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected",
"true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});
$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor",
"#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color","#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});
return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",
g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});$.widget("fb.fbCheckBox",FbCheckBox);
var hrefid="link",FbPlainTextHref=$.extend({},$.fb.fbWidget.prototype,{options:{name:"HyperLink",belongsTo:$.fb.formbuilder.prototype.options._standardFieldsPanel,_type:"PlainTextHref",_html:'<div><a href="#" id="link"> \t      <label><span>Your HyperLink</span></label></a>  </div>',_counterField:"label",_languages:["en","zh_CN"],settings:{en:{label:"link",value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},zh_CN:{label:"\ufffd?\ufffd\u884c\u6587\u5b57\u8f93\u5165",
value:"",description:"",styles:{fontFamily:"default",fontSize:"default",fontStyles:[0,0,0]}},_persistable:true,required:true,restriction:"no",styles:{label:{color:"default",backgroundColor:"default"},value:{color:"default",backgroundColor:"default"},description:{color:"777777",backgroundColor:"default"}}}},_init:function(){$.fb.fbWidget.prototype._init.call(this);this.options=$.extend({},$.fb.fbWidget.prototype.options,this.options)},_getWidget:function(c,a){hrefid="link";var b=$(a.target.options._html);
$("label span",b).text(a.settings.label);a._settings.required&&$("label em",b).text("*");$("input",b).val(a.settings.value);$(".formHint",b).text(a.settings.description);return b},_getFieldSettingsLanguageSection:function(c,a){var b=a.target._label({label:"Label",name:"field.label"}).append('<input type="text" id="field.label" />');$("input",b).val(a.settings.label).keyup(function(){var d=$(this).val();a.item.find("label span").text(d);a.settings.label=d;a.target._updateSettings(a.item);a.target._updateName(a.item,
d)});var g=a.target._label({label:"Value",name:"field.value"}).append('<input type="text" id="field.value" />');$("input",g).val(a.settings.value).keyup(function(){var d=$(this).val(),i=d.length;$("#"+hrefid).attr("href",d);$("#"+hrefid).attr("id",i);hrefid=i;a.settings.value=d;a.target._updateSettings(a.item)});var h=a.target._label({label:"Description",name:"field.description"}).append('<textarea id="field.description" rows="2"></textarea>');$("textarea",h).val(a.settings.description).keyup(function(){var d=
$(this).val();a.item.find(".formHint").text(d);a.settings.description=d;a.target._updateSettings(a.item)});var e=a.settings.styles,f=a.target._getFbLocalizedSettings().styles;f=a.target._fontPanel({fontFamily:e.fontFamily!="default"?e.fontFamily:f.fontFamily,fontSize:e.fontSize!="default"?e.fontSize:f.fontSize,fontStyles:e.fontStyles,idPrefix:"field.",nofieldset:true});$("input[id$='field.bold']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontWeight","bold");a.item.find(".textInput").css("fontWeight",
"bold");e.fontStyles[0]=1}else{a.item.find("label").css("fontWeight","normal");a.item.find(".textInput").css("fontWeight","normal");e.fontStyles[0]=0}a.target._updateSettings(a.item)});$("input[id$='field.italic']",f).change(function(){if($(this).attr("checked")){a.item.find("label").css("fontStyle","italic");a.item.find(".textInput").css("fontStyle","italic");e.fontStyles[1]=1}else{a.item.find("label").css("fontStyle","normal");a.item.find(".textInput").css("fontStyle","normal");e.fontStyles[1]=
0}a.target._updateSettings(a.item)});$("input[id$='field.underline']",f).change(function(){if($(this).attr("checked")){a.item.find("label span").css("textDecoration","underline");a.item.find(".textInput").css("textDecoration","underline");e.fontStyles[2]=1}else{a.item.find("label span").css("textDecoration","none");a.item.find(".textInput").css("textDecoration","none");e.fontStyles[2]=0}a.target._updateSettings(a.item)});$("input[id$='field.fontFamily']",f).change(function(){var d=$(this).val();a.item.css("fontFamily",
d);a.item.find(".textInput").css("fontFamily",d);e.fontFamily=d;a.target._updateSettings(a.item)});$("select[id$='field.fontSize']",f).change(function(){var d=$(this).val();a.item.find("label").css("fontSize",d+"px");a.item.find(".textInput").css("fontSize",d+"px");e.fontSize=d;a.target._updateSettings(a.item)});return[a.target._twoColumns(b,g),a.target._oneColumn(h),f]},_getFieldSettingsGeneralSection:function(c,a){var b=$('<div><input type="checkbox" id="field.required" />&nbsp;Required</div>'),
g=$('<div><select id="field.restriction" style="width: 99%"> \t\t\t\t<option value="no">any character</option> \t\t\t\t<option value="alphanumeric">alphanumeric only</option> \t\t\t\t<option value="letterswithbasicpunc">letters or punctuation only</option> \t\t\t\t<option value="lettersonly">letters only</option> \t\t\t</select></div>'),h=a.target._fieldset({text:"Value"}).append(a.target._twoColumns(b,g));$(".col1",h).css("width","32%").removeClass("labelOnTop");$(".col2",h).css("marginLeft","34%").removeClass("labelOnTop");
$("input",b).attr("checked",a.settings.required).change(function(){if($(this).attr("checked")){a.item.find("em").text("*");a.settings.required=true}else{a.item.find("em").text("");a.settings.required=false}a.target._updateSettings(a.item)});$("select option[value='"+a.settings.restriction+"']",g).attr("selected","true");$("select",g).change(function(){a.settings.restriction=$(this).val();a.target._updateSettings(a.item)});var e=a.item.find(".textInput"),f=a.settings.styles;if(f.value.color=="default")f.value.color=
e.css("color");if(f.value.backgroundColor=="default")f.value.backgroundColor=e.css("backgroundColor");b=a.target._labelValueDescriptionColorPanel(f);$("input[id$='field.label.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("color","#"+d);f.label.color=d;a.target._updateSettings(a.item)});$("input[id$='field.label.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.css("backgroundColor","#"+d);f.label.backgroundColor=d;a.target._updateSettings(a.item)});
$("input[id$='field.value.color']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("color","#"+d);f.value.color=d;a.target._updateSettings(a.item)});$("input[id$='field.value.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;e.css("backgroundColor","#"+d);f.value.backgroundColor=d;a.target._updateSettings(a.item)});$("input[id$='field.description.color']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("color",
"#"+d);f.description.color=d;a.target._updateSettings(a.item)});$("input[id$='field.description.backgroundColor']",b).change(function(){var d=$(this).data("colorPicker").color;a.item.find(".formHint").css("backgroundColor","#"+d);f.description.backgroundColor=d;a.target._updateSettings(a.item)});return[h,b]},_languageChange:function(c,a){var b=a.settings.styles,g=a.target._getFbLocalizedSettings().styles,h=b.fontFamily!="default"?b.fontFamily:g.fontFamily;g=b.fontSize!="default"?b.fontSize:g.fontSize;
var e=b.fontStyles[0]==1?"bold":"normal",f=b.fontStyles[1]==1?"italic":"normal";b=b.fontStyles[2]==1?"underline":"none";a.item.css("fontFamily",h);a.item.find("label span").text(a.settings.label).css("textDecoration",b);a.item.find("label").css("fontWeight",e).css("fontStyle",f).css("fontSize",g+"px");a.item.find(".textInput").val(a.settings.value).css("fontWeight",e).css("fontStyle",f).css("textDecoration",b).css("fontFamily",h).css("fontSize",g+"px");a.item.find(".formHint").text(a.settings.description)}});
$.widget("fb.fbPlainTextHref",FbPlainTextHref);
